// <auto-generated />
using System;
using FlowerShop.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FlowerShop.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.26");

            modelBuilder.Entity("FlowerShop.API.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("CourierId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DeliveryTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("FloristId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("FlowerShop.API.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("FlowerShop.API.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<double>("Rating")
                        .HasColumnType("REAL");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Букеты",
                            Description = "Красивый и нежный букет из свежих хризантем",
                            ImageUrl = "/images/bouquet1.jpg",
                            IsAvailable = true,
                            Name = "Нежный букет из кустовой персиковой хризантемой",
                            Price = 2925m,
                            Rating = 4.9500000000000002,
                            Stock = 10
                        },
                        new
                        {
                            Id = 2,
                            Category = "Букеты",
                            Description = "Изысканный букет с французскими розами",
                            ImageUrl = "/images/bouquet2.jpg",
                            IsAvailable = true,
                            Name = "Lace bouquet with French rose",
                            Price = 3362m,
                            Rating = 4.8799999999999999,
                            Stock = 8
                        },
                        new
                        {
                            Id = 3,
                            Category = "Букеты",
                            Description = "Пионовидные розы Silva pink в двойной корзине",
                            ImageUrl = "/images/bouquet3.jpg",
                            IsAvailable = true,
                            Name = "Duobucket of peony-shaped roses",
                            Price = 2943m,
                            Rating = 4.8200000000000003,
                            Stock = 5
                        },
                        new
                        {
                            Id = 4,
                            Category = "Букеты",
                            Description = "Букет из пионовидных роз Silva pink и Bombastic",
                            ImageUrl = "/images/bouquet4.jpg",
                            IsAvailable = true,
                            Name = "Bouquet of peony-shaped roses",
                            Price = 3995m,
                            Rating = 4.6699999999999999,
                            Stock = 3
                        });
                });

            modelBuilder.Entity("FlowerShop.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 5, 19, 10, 49, 15, 484, DateTimeKind.Utc).AddTicks(7659),
                            Email = "admin@flowershop.com",
                            FullName = "System Administrator",
                            PasswordHash = "$2a$11$KjX8Yx9ZxLmNpOqRtSuVvWxYzAbCdEfGhIjKlMnOpQrStUvWxYzA",
                            Phone = "+70000000000",
                            Role = 3
                        });
                });

            modelBuilder.Entity("FlowerShop.API.Models.OrderItem", b =>
                {
                    b.HasOne("FlowerShop.API.Models.Order", null)
                        .WithMany("Items")
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FlowerShop.API.Models.Order", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
